#Requires -Version 7

<#
.SYNOPSIS
    Generates production Helm secret values for the oci-prod Skaffold profile.

.DESCRIPTION
    Writes values.oci-prod.secrets.yaml for both the lobbies and game charts.

    The GameAuth JWT signing secret is shared between the two services: it is
    generated once and written to both files, so the two charts can never drift
    out of sync. JWT validation fails silently on a mismatch, so a single
    generation step is the point of this script.

    The oci-prod Skaffold profile already lists both files under each release's
    valuesFiles, so `skaffold run -p oci-prod` picks them up automatically.

    The generated files contain live secrets and are gitignored. Existing files
    are not overwritten unless -Force is passed: regenerating rotates every
    secret, which breaks an already-running deployment until both charts are
    redeployed.

.PARAMETER Force
    Overwrite existing secret files, rotating all generated secrets.
#>
[CmdletBinding()]
param(
    [switch] $Force
)

$ErrorActionPreference = 'Stop'

$repoRoot    = $PSScriptRoot
$lobbiesFile = Join-Path $repoRoot 'src/YARG.Online.Lobbies/charts/values.oci-prod.secrets.yaml'
$gameFile    = Join-Path $repoRoot 'src/YARG.Online.Game/charts/values.oci-prod.secrets.yaml'

foreach ($f in @($lobbiesFile, $gameFile)) {
    if ((Test-Path $f) -and -not $Force) {
        throw "$f already exists. Pass -Force to regenerate (this rotates the secrets and requires redeploying both charts)."
    }
}

# Cryptographically random secret, base64-encoded. 32 bytes -> 44 chars, which
# also satisfies the >=256-bit key length HMAC-SHA256 JWT signing requires.
function New-Secret([int] $bytes = 32) {
    [Convert]::ToBase64String([System.Security.Cryptography.RandomNumberGenerator]::GetBytes($bytes))
}

# --- secret shared between both charts (must be byte-identical) ---
$gameAuthSigningSecret = New-Secret

# --- lobby-only secret (player-facing auth) ---
$playerAuthSigningSecret = New-Secret

# --- non-secret identity / wiring values ---
$authIssuer       = 'yarg-online'
$authAudience     = 'yarg-online'
$gameAuthIssuer   = 'yarg-online-game'
$gameAuthAudience = 'yarg-online-game'
# Internal-only Gateway for the lobbies game-server callbacks (ClusterIP Envoy,
# restricted to game-server pods by NetworkPolicy). Port 80, not the pod's 5230.
$lobbiesBaseUrl   = 'http://lobbies-internal-gateway.yarg-online-envoy-gateway-system.svc.cluster.local/'

$lobbiesYaml = @"
# Generated by New-ProdSecrets.ps1 -- do not edit by hand, do not commit.
# Loaded by the oci-prod Skaffold profile alongside values.oci-prod.yaml.
secrets:
  Auth__Issuer: '$authIssuer'
  Auth__Audience: '$authAudience'
  Auth__SigningSecret: '$playerAuthSigningSecret'
  GameAuth__Issuer: '$gameAuthIssuer'
  GameAuth__Audience: '$gameAuthAudience'
  GameAuth__SigningSecret: '$gameAuthSigningSecret'
"@

$gameYaml = @"
# Generated by New-ProdSecrets.ps1 -- do not edit by hand, do not commit.
# Loaded by the oci-prod Skaffold profile alongside values.oci-prod.yaml.
secrets:
  GameAuth__Issuer: '$gameAuthIssuer'
  GameAuth__Audience: '$gameAuthAudience'
  GameAuth__SigningSecret: '$gameAuthSigningSecret'
  Lobbies__BaseUrl: '$lobbiesBaseUrl'
"@

Set-Content -Path $lobbiesFile -Value $lobbiesYaml -Encoding utf8
Set-Content -Path $gameFile    -Value $gameYaml    -Encoding utf8

Write-Host "Wrote $lobbiesFile"
Write-Host "Wrote $gameFile"
Write-Host "Shared GameAuth signing secret is consistent across both charts."
Write-Host "Deploy with: skaffold run -p oci-prod"
