{{- if .Values.agones.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-lobbies
  labels:
    app.kubernetes.io/name: yarg-online-lobbies
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
